import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Test from '../components/Test'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* title */}
      <Head>
        <title>ポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ヘッダー */}
      <header className="flex justify-between items-center mx-10">
        <Link href="/">
          <a className="hover:opacity-80">
            <Image src="/logo.png" alt="ロゴ画像" width="192" height="96" />
          </a>
        </Link>
        <ul className="flex mr-6 space-x-8 text-lg font-bold text-green">
          <li className="hover:opacity-80 hover:transition-all">
            <Link href="#about">
              <a>ABOUT</a>
            </Link>
          </li>
          <li className="hover:opacity-80">
            <Link href="#skill">
              <a>SKILL</a>
            </Link>
          </li>
          <li className="hover:opacity-80">
            <Link href="#value">
              <a>VALUE</a>
            </Link>
          </li>
          <li className="hover:opacity-80">
            <Link href="#future">
              <a>FUTURE</a>
            </Link>
          </li>
        </ul>
      </header>

      {/* メインコンテンツ */}
      <main>
        <div className="flex justify-between items-center px-16 h-[450px] bg-lightGreen">
          <div className="text-white">
            <h1 className="text-6xl leading-loose">
              <span className="text-Orange">M</span>asahiro
              <span className="text-Orange">K</span>oumura
              <span className="text-Orange">P</span>ortfolio
            </h1>
            <p className="text-2xl text-lightBlue">
              WEBデザイナー/フロントエンドエンジニア/WEBディレクター、
              <br />
              Masahiro Koumuraのポートフォリオです。
            </p>
          </div>
          <Image src="/hero.png" alt="イメージ画像" width="390" height="332" />
        </div>

        {/* 私について */}
        <div className="py-14 w-full bg-cover bg-about-img">
          <div className="flex justify-center items-center pb-12 font-bold">
            <h2 className="text-3xl text-center">私について</h2>
            <p className="px-4 text-xl text-green">- ABOUT -</p>
          </div>

          <div className="flex my-0 mx-auto space-x-6 w-[960px]">
            <div className="w-2/6 text-center">
              <div className="h-[160px]">
                <Image src="/about-1.png" alt="趣味" width="184" height="157" />
              </div>
              <h3 className="my-6 text-2xl font-bold text-green">趣味</h3>
              <p className="leading-relaxed text-left">
                テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
              </p>
            </div>
            <div className="w-2/6 text-center">
              <div className="h-[160px]">
                <Image src="/about-2.png" alt="趣味" width="206" height="158" />
              </div>
              <h3 className="my-6 text-2xl font-bold text-center text-green">
                好きな食べ物
              </h3>
              <p className="leading-relaxed text-left">
                テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
              </p>
            </div>
            <div className="w-2/6 text-center">
              <div className="h-[160px]">
                <Image src="/about-3.png" alt="趣味" width="245" height="149" />
              </div>
              <h3 className="my-6 text-2xl font-bold text-center text-green">
                性格
              </h3>
              <p className="leading-relaxed text-left">
                テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
              </p>
            </div>
          </div>
        </div>

        {/* スキル */}
        <div className="py-14 bg-lightBackBlue">
          <div className=" flex justify-center items-center pb-12 font-bold">
            <h2 className="text-3xl text-center">スキル</h2>
            <p className="px-4 text-xl text-green">- SKILL -</p>
          </div>
          <div className="flex my-0 mx-auto space-x-6 w-[960px]">
            <div className="w-3/6">
              <Image src="/skill.png" alt="スキル" width="535" height="372" />
            </div>
            <div className="flex flex-wrap w-3/6">
              <p className="leading-relaxed">
                テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
              </p>
              <div className="w-full bg-white rounded-md">
                <ul>
                  <li>HTML5</li>
                  <li>CSS3</li>
                  <li>React</li>
                  <li>Next.js</li>
                  <li>TypeScript</li>
                  <li>JavaScript</li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        {/* 価値観 */}
        <div className="flex justify-center items-center py-12 font-bold">
          <h2 className="text-3xl text-center">価値観</h2>
          <p className="px-4 text-xl text-green">- VALUE -</p>
        </div>

        {/* 3年後にやりたいこと */}
        <div className="flex justify-center items-center py-12 font-bold">
          <h2 className="text-3xl text-center">3年後にやりたいこと</h2>
          <p className="px-4 text-xl text-green">- FUTURE -</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
